### ISSUE TITLE
Show critical damage in stats when leader has Critical hit ability

### ISSUE THREAD

**Issue by Positiff88** [VladimirMakeev/D2ModdingToolset#105]
Просьба добавить отображение величины и точности критического урона в окне характеристик лидера когда он имеет способность Критический удар (L_CRITICAL_HIT с идентификатором 17 в файле LleadA.dbf). Эту способность можно изучить на 15 уровне если играешь за лорда Полководец, но в характеристиках бонусный урон при этом не отображается, а хотелось бы чтоб он отображался так же как и у юнитов с критическим ударом.

**Comment by VladimirMakeev** [comment]
Скорее всего это будет сделано в скором времени вместе с исправлением падения игры при просмотре информации о некоторых юнитах.

**Comment by UnveN** [comment]
@VladimirMakeev @Positiff88 
Сделано https://github.com/VladimirMakeev/D2ModdingToolset/commit/d790d71eb14b85d54b574d7ebdfcef75cce1aec7

**Comment by Positiff88** [comment]
Благодарю.
