### ISSUE TITLE
Добавление новых веток для юнитов

### ISSUE THREAD

**Issue by Degrees9871** [VladimirMakeev/D2ModdingToolset#106]
Добрый день. Добавляет ли ваша модификация возможность изменять количество веток развития для юнитов? Если нет, то насколько сложно это реализовать?

**Comment by VladimirMakeev** [comment]
Новая ветка сделана фиктивно специально для дополнительных юнитов в моде Норвежской Семги.
Полноценных новых веток нет, сделать не просто, требуется много правок в разных местах игровой логики.

**Comment by Degrees9871** [comment]
по поводу ограничения на постройку нескольких зданий в ветке L_CUSTOM. Сейчас максимум 1 здание в этой категории. Вы умышленно ограничились 1 зданием потому что при нескольких - сложности возникают?
Если мы к примеру подвяжем несколько типов категорий (L_CUSTOM2, L_CUSTOM3) к постройке, насколько трудно это реализовать? Я сам готов попробовать сделать, но мне нужно ваше мнение по поводу оценки сложности (можно ли браться не специалисту)
Если есть смысл, приложите пожалуйста список файлов для редактирования)

**Comment by Degrees9871** [comment]
пару строчек добавить, разобрался
