### ISSUE TITLE
Храм для Воина по-умолчанию

### ISSUE THREAD

**Issue by InnerLight** [VladimirMakeev/D2ModdingToolset#132]
Нет построенного храма для лидера Воина (Руссобит-М).
Даже на ванильных картах и сагах, когда новую запускаешь. 
Сами карты не пересохранял.

```
-- Allow scenarios with prebuilt capital cities
preserveCapitalBuildings = true,
-- Start with pre built temple in capital for warrior lord
buildTempleForWarriorLord = true,
```

dll и скрипты последние (16.07.2022 скачал)

**Comment by InnerLight** [comment]
`-- Allow scenarios with prebuilt capital cities
preserveCapitalBuildings = false,
-- Start with pre built temple in capital for warrior lord
buildTempleForWarriorLord = true,`

так тоже не работает

**Comment by VladimirMakeev** [comment]
Эта фича войдет в следующий релиз, в версии 0.11 ее нет.
