### ISSUE TITLE
Info about build process and requirements

### ISSUE THREAD

**Issue by Positiff88** [VladimirMakeev/D2ModdingToolset#214]
Пожалуйста добавьте в проект информацию касательно процесса сборки решения. Какая нужна версия Visual Studio? Какой должен быть Стандарт языка C++, если это важно? Какими в свойствах проекта должны быть Версия пакета SDK для Windows и Набор инструментов платформы?

Уже несколько дней безрезультатно пытаюсь собрать проект чтобы внести свои правки. Зависимости вроде удалось собрать с горем пополам, а вот mss32 пока никак. Выдаёт кучу ошибок вида:
Ошибка	C2027	использование неопределенного типа "std::_Get_first_parameter<_Ty>"	xmemory0	266

Мои параметры:
Среда разработки - Visual Studio 2017
Стандарт языка - Стандарт ISO C++17 (/std:c++17)
Версия пакета SDK для Windows - Visual Studio 2017 (v141)
Набор инструментов платформы - 10.0.17763.0

**Comment by VladimirMakeev** [comment]
Я собирал проект с помощью Visual Studio 2019 и 2022. [Стандарт](https://github.com/VladimirMakeev/D2ModdingToolset/blob/master/mss32/mss32.vcxproj#L92) языка, [версию](https://github.com/VladimirMakeev/D2ModdingToolset/blob/master/mss32/mss32.vcxproj#L30) пакета SDK и набор инструментов платформы можно оставить по умолчанию как они заданы в файлах соотв. подпроектов.
Достаточно скачать репозиторий вместе с сабмодулями (зависимостями) и нажать Build в Visual Studio. Зависимости соберутся сами.
Также, стоит задать переменную окружения `DISCIPLES2_PATH` указав папку с игрой, это позволит быстро проверять внесенные изменения.

**Comment by Positiff88** [comment]
Я пробовал собрать решение в Visual Studio 2019 таким образом:
Клонирую сперва D2ModdingToolset. Проект скачивается, но с пустыми папками D2RSG, Detours, fmt, GSL, SLikeNet, sol2. Тогда я клонирую каждый из перечисленных проектов в соответствующую подпапку внутри D2ModdingToolset. После этого пытаюсь собрать решение mss32, но возникает ошибка:
C1083	Не удается открыть файл включение: sol/sol.hpp: No such file or directory,	ScenarioGenerator	C:\Repos\D2ModdingToolset\D2RSG\ScenarioGenerator\src\generatorsettings.cpp	29	

Может я что-то делаю не так? Как правильно скачать репозиторий вместе с зависимостями?

**Comment by VladimirMakeev** [comment]
Отвечаю на английском чтобы было понятно всем.
Writing in english for @Haikyo-sama as well

1. Clone repo and **initialize** all its submodules
<img width="300" alt="git clone" src="https://github.com/VladimirMakeev/D2ModdingToolset/assets/16177408/91755ee8-0cc7-4de2-9d9c-b64de85e049a">

2. Open <a href="https://github.com/VladimirMakeev/D2ModdingToolset/blob/master/mss32/mss32.sln">mss32.sln</a> using Visual Studio Community 2019 or 2022, don't change SDK or platform toolset:
<img width="403" alt="project upgrade" src="https://github.com/VladimirMakeev/D2ModdingToolset/assets/16177408/47c60117-9a26-462e-8aa7-2ed3fc033747">

3. Setup environment variable `DISCIPLES2_PATH` with path to your Disciples 2 Rise of the Elves 3.01 game. Use that variable in mss32 project settings so after build library will be placed there. Don't forget to rename original mss32.dll to **mss23.dll**
<img width="711" alt="common settings" src="https://github.com/VladimirMakeev/D2ModdingToolset/assets/16177408/b19f57df-f5a5-4eca-828e-a7a8e872d156">

4. Setup debug path at working directory accordingly:
<img width="711" alt="debug settings" src="https://github.com/VladimirMakeev/D2ModdingToolset/assets/16177408/aa42ee2d-a55e-4af3-8209-89d075b40fee">

5. Build mss32 project and run 'Debug', the game will start with debugger attached to our proxy dll. Any breakpoints that you set will work as expected:
<img width="416" alt="debug" src="https://github.com/VladimirMakeev/D2ModdingToolset/assets/16177408/c3d74211-76ca-4123-aabc-18fab8f1ac13">

**Comment by Positiff88** [comment]
**Build produces the following error:**
The BaseOutputPath/OutputPath property is not set for project 'mss32.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win32'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.	mss32	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	820

**Comment by Positiff88** [comment]
Seems that this error happened because I've added DISCIPLES2_PATH system variable while my Visual Studio was opened. Problem vanished when I restarted it.

**Comment by Positiff88** [comment]
I've successfully build the project. Thanks for help.
