### ISSUE TITLE
Multiple attack types

### ISSUE THREAD

**Issue by InnerLight** [VladimirMakeev/D2ModdingToolset#61]
Здравствуйте, хотелось бы иметь возможность совмещать разные типы атак у юнитов, напр:
Атакующие/защитные, атакующие/призывные.

Примеры конкретных комбинаций: Алхимик у Гномов, который смог бы давать ход своим или отравлять врагов.
Повелитель стихий (Элементалист), который атакует противника или вызывает элементалей.
Лорд Тьмы, атакующий либо дающий защиту от магии стихий.
Вызыватели, которые альтернативной атакой могли бы бафать союзников и т.д.

Сейчас этого не хватает для создания гибких персонажей при прокачке.

**Comment by VladimirMakeev** [comment]
Каждый тип атаки в игре ["знает"](https://github.com/VladimirMakeev/D2ModdingToolset/blob/master/mss32/include/batattack.h#L56) какой из отрядов является целевым: вражеский или союзный - это зашито в самой логике боя.
В данный момент совмещать разные типы атак можно только через "превращение себя" (L_TRANSFORM_SELF). Т.е. можно сделать "алхимика" который  дает доп. ход союзникам и превращет себя в юнита который отравляет врагов и способен к обратной трансформации в "алхимика". Такой подход использован в моде от [Honests Games](https://www.youtube.com/watch?v=mfdX6iVYZes).
В планах добавление полностью скриптовых атак которые позволят создавать подобные механики без превращений. Это потребует замены большой части логики боя, а также поддержку новых анимаций, звуков и ресурсов в целом, поэтому точных сроков назвать не смогу.

**Comment by InnerLight** [comment]
Спасибо большущее, открыли новый мир модификацией от Honest Games!!

Чисто теоретический вопрос, а можно в целом реализовать систему апргейдов наподобие Легенд Эйзенвальда?
Строим здания из двух-трёх веток юнита, при повышении выбираем по какой ветке желает развиваться.

Пример из моего концепта: 
https://steamcommunity.com/sharedfiles/filedetails/?id=645828880
https://steamcommunity.com/sharedfiles/filedetails/?id=645827867

**Comment by VladimirMakeev** [comment]
В теории можно сделать все, если потратить на это много времени и усилий.
Помимо Honests Games есть и другие не менее интересные и популярные моды, каждый со своей спецификой. А также сообщество фанатов игры в [Discord](https://discord.gg/kBSj4JgRCV) где в том числе обсуждается разработка.
