### ISSUE TITLE
Точка входа в процедуру _AIL_set_preference@8 не найдена в библиотеке Discipl2.exe

### ISSUE THREAD

**Issue by InnerLight** [VladimirMakeev/D2ModdingToolset#65]
После установки мода выдаёт такую ошибку. Что с настроенными скриптами, что сразу после установки.
Russobit-M лицензия (для запуска эмулирую первый диск)

![image](https://user-images.githubusercontent.com/29140137/133126258-27a28009-3052-491f-8516-955463498718.png)
[Discipl2.exe.crash.txt](https://github.com/VladimirMakeev/D2ModdingToolset/files/7156143/Discipl2.exe.crash.txt)

**Comment by VladimirMakeev** [comment]
Убедитесь что оригинальная mss32.dll в папке с игрой была переименована в mss23.dll перед копированием файлов из релиза этого репозитория.

**Comment by InnerLight** [comment]
Удивительно, не думал, что работа новой dll завязана на оригинальной ))
оригинальную просто добавлял в архив и заменял версией из мода.

Не критично, спасибо за помощь, ушёл мододельствовать на новом уровне :)
