### ISSUE TITLE
Additional Unit Interface Info 

### ISSUE THREAD

**Issue by InnerLight** [VladimirMakeev/D2ModdingToolset#71]
Добрый день, Vladimir!

Будьте добры, добавьте возможность выводить в карточку юнита дополнительную информацию.
Было бы здорово выводить информацию согласно содержимому скрипту lua (в идеале выбирать к какому элементу интерфейса она относится).

Я бы очень хотел видеть такую инфу, как, например, регенерацию - очень знаете ли важная и полезная вещь и для PvE и PvP :wink: 

Пример:
![image](https://user-images.githubusercontent.com/29140137/135733252-0b6a2227-adb5-47d4-ad0b-7d3ec99455f5.png)

**Comment by VladimirMakeev** [comment]
Есть программа Disciples2Info, которая показывает расширенную информацию о юнитах и не только.
Скачать можно [здесь](https://norvezskayasemga.pro/download), раздел Disciples2Info.

**Comment by InnerLight** [comment]
> Есть программа Disciples2Info, которая показывает расширенную информацию о юнитах и не только. Скачать можно [здесь](https://norvezskayasemga.pro/download), раздел Disciples2Info.

Имею ввиду в самой игре, в т.ч. в бою. Регенерация юнита может быть изменена в сценарии, оттого в энциклопедии типа Disciples2Info данные будут неточны, что введёт в заблуждение и может привести к проигрышу партии.

**Comment by InnerLight** [comment]
В принципе, если в названии юнита или где-то в существующих реквизитах добавить инфу о регенерации, то этого на первых порах будет достаточно и будет совершён мощный прорыв.

В файлах даже редактора не нашёл % регенерации юнита. Это зашито во внутренние переменные (напр. %VAR% в редакторе, когда добавляется + 10 регенерации юнита, либо %HP% в описании поселений на карте).
Проверял и %HP%, и  %HP3%, и %REG%, и %REGEN%, и %VAR% - ничего из этого в карточку бойца не попадает (пробовал вставлять вместо значения Уровень).

**Comment by VladimirMakeev** [comment]
Я не планирую в ближайшее время менять отображение информации юнитов. Тащить туда lua тем более.
Логика отображения разобрана и поправлена под новые дальности атак, так что если есть желание расширить, то это нужно можно [здесь](https://github.com/VladimirMakeev/D2ModdingToolset/blob/master/mss32/src/interftexthooks.cpp#L655). Там же можно посмотреть как сделано отображение других статов и сделать по примеру.

**Comment by InnerLight** [comment]
Спасибо
