### ISSUE TITLE
Artefact attack info is lacked

### ISSUE THREAD

**Issue by InnerLight** [VladimirMakeev/D2ModdingToolset#72]
Если на герое одет артефакт, дающий атаку, то она не отображается в карточке Героя:

**Артефакт:**
![ScreenShot019](https://user-images.githubusercontent.com/29140137/136672953-a7e7bfff-c7a5-4cbf-8e00-cfa835b37430.png)

**Карточка героя:**
![ScreenShot021](https://user-images.githubusercontent.com/29140137/136672958-d56e7ffd-b82a-4c2e-a5d8-1047e737076c.png)

**Comment by VladimirMakeev** [comment]
Это не связано с версий mss, оригинальная игра также не отображает в описании юнита атаки полученные от артефактов .
