### ISSUE TITLE
Extra bonus for a Warrior lord

### ISSUE THREAD

**Issue by Positiff88** [VladimirMakeev/D2ModdingToolset#75]
**Proposal:**
It will be nice to have an option to preconstruct a Temple building when a Warrior lord is taken and to add an extra bonus for his armies (in my opinion the most interesting bonus is +25% of an extra experience for all units, but it also can be an extra health, initiative, accuracy, damage or armor).

**Justification:**
Unfortunately, a Warrior lord is the weakest one among the lords at the moment. Unlike Mage and Diplomat lords (who has a Magic Tower and Guild buildings at the start), a Warrior lord has no preconstructed building and gives only 15% regeneration bonus, which is nothing against bonuses of Mage lord (spent 50% less resources for spell research and can cast spells two times per day) and Diplomat lord (building of the cities is 50% cheeper and Thief has much more abilities).

**Comment by VladimirMakeev** [comment]
Added option 'buildTempleForWarriorLord' to settings.lua that allows to start scenarios with pre build temple for warrior lord.
Additional bonuses not implemented yet, btw extra health is difficult to add.

**Comment by Positiff88** [comment]
Nice news! I hope that it is not so difficult to add the other mentioned bonuses, especially experience and armor, which in a certain way help to counteract the ability to cast attacking spells twice (after all, armor reduces damage, and upgraded units have more health).

**Comment by VladimirMakeev** [comment]
I'm thinking about changing the whole battle system so it will be scripted and configurable as much as possible. It's a huge amount of work with a huge potential.
Can't tell how long would it take to do, there are some parts of battle and AI logic that needs to be reverse-engineered prior to starting.
With that in mind I think exp, armor and accuracy computation will be a part of this system.

**Comment by UnveN** [comment]
@Positiff88 В то время пока мы еще не добавили возможности давать бонусы лордам, появилась возможность давать бонусы юнитам в зависимости от того какому лорду они служат.

Сделано по средствам врожденных модификаторов - т.е. модификаторов которые можно привязать к юниту с момента его "рождения", а-ля банка с перманентным эффектом выданная в роддоме.
См. раздел "Supports native unit modifiers" в https://github.com/VladimirMakeev/D2ModdingToolset#readme.
Можно использовать как стандартные так и кастомные модификаторы (см. Supports custom unit modifiers).

В данном случае целесообразным видится добавление глобального кастомного модификатора всем юнитам, в его коде делать проверку на хозяина-лорда.
Как сделать такую проверку - см. доки по скриптовому API https://github.com/VladimirMakeev/D2ModdingToolset/blob/master/luaApi.md
Учти, что добавление глобального модификатора скажется на быстродействии.

**Comment by Positiff88** [comment]
Спасибо огромное! Буду пробовать.

**Comment by Positiff88** [comment]
I've implemented +15% extra experience bonus using native unit modifiers and custom attack reaches.
