### ISSUE TITLE
Global settings with daily income of the cities

### ISSUE THREAD

**Issue by Positiff88** [VladimirMakeev/D2ModdingToolset#76]
Please add a global settings with daily income of the cities, which will affect income on any scenario or campaign without the need to add a scenario variables. In this case a scenario variables should be used to override a daily income of the cities in a particular scenario. This global settings will be used as a part of the mod, which affects game economy.

**Comment by Positiff88** [comment]
Получится ли такое реализовать? Было бы очень круто иметь возможность указать добываемое городами всех рас золото в каком-то одном месте (например, в настройках Scripts\settings.lua или в файле Globals\GVars.dbf в колонках GOLD_CITY1 и т.д.), чтобы эти изменения сразу заработали на всех старых сценариях и сагах без необходимости обновлять карты и добавлять переменные, т.е. чтобы доход от городов мог регулировать автор мода игры, а не только автор карт для неё.

Кстати, сейчас в сагах доход городов не работает (пробовал добавлять переменные типа TIER_1_CITY_INCOME в файл Scens\SVars.dbf). Большая просьба хотя бы это исправить по возможности!

**Comment by VladimirMakeev** [comment]
Доход городов через переменные сценария работает в кастомных и встроенных в игру, "ванильных", сагах.
Помимо добавления переменной в SVars.dbf нужно также увеличить количество переменных в SCount.dbf, т.е. найти строку с нужным id сценария в колонке NO_SCEN у которой в колонке TYPE будет значение VARIABLES и указать в столбце COUNT нужное число.

**Comment by Positiff88** [comment]
Не помогло. Пробовал на примере саги Защитников Империи, для которой в оригинале не было переменных, соответственно, нужные записи я добавлял с нуля. Добавил значения для первой карты саги (NO_SCEN = S107SC0000) в файлы SVars.dbf и SCount.dbf, а также по примеру другой карты с переменными пробовал добавлять запись в SObjMap.dbf со значением колонки WHAT равным .?AVCMidScenVariables@@ и соответствующим OBJ_ID, равным значению ID записи в SCount.dbf (S107SV0000). Может что-то ещё нужно сделать?

Кстати, неплохо бы добавить в описание возможностей D2ModdingToolset небольшую инструкцию по добавлению переменных с доходом городов в ванильные саги (то есть в какие файлы и что нужно прописывать). А то это совсем не очевидно с ходу...

**Comment by VladimirMakeev** [comment]
Тогда стоит упростить задачу, добавить новую переменную в карту сценария где уже одна переменная есть. Для этого достаточно новой записи в SVars.dbf и увеличения соответствующего счетчика переменных в SCount.dbf. Я проверял на 2 миссии в саге эльфов.

D2ModdingToolset задумывался для расширения возможностей мододелов и описания (восстановления) кодовой базы игры. Предполагается что мододел сам разберется в том как моддить игру, создать и вести исчерпывающее руководство по моддингу я не готов.

**Comment by Positiff88** [comment]
Не вижу смысла добавлять доход городам в сагах если это нельзя сделать на всех картах. Это будет нецелостно и странно. Собственно, поэтому мне и видится правильным добавление единой настройки вместо переменных на каждой карте, если это технически возможно сделать. С учётом уже реализованного дохода с использованием переменных видится ли тебе реализация единых настроек реальной?

**Comment by Positiff88** [comment]
Радует, что это возможно. Буду очень благодарен, если сделаешь! Только вот не вижу особого смысла в **складывании** всех настроек, ведь автор карты явно не ожидал, что к указанным им суммам дохода в будущем что-то прибавится - он рассчитывал именно на эти конкретные суммы по своим соображениям дизайна карты. Аналогично и мододел ожидал бы, что будет применяться именно доход, указанный им в settings.lua, если только автор карты не указал другие значения для данной конкретной карты.

Нельзя ли сделать логику несколько иной, т.е. такой как она описана в предложении? Чтобы изначально применялся доход указанный в глобальной настройке, а если в сценарии заданы свои переменные, то их сумма используется **вместо** значения из глобальной настройки.

Чтобы было условно так:
`TIER_N_CITY_INCOME + <RACE>_TIER_N_CITY_INCOME > 0 ? TIER_N_CITY_INCOME + <RACE>_TIER_N_CITY_INCOME : settings[race][tier]`

**Comment by VladimirMakeev** [comment]
Нет, я выше писал что против замены значений. Это не очевидно и не решает проблем с "поломкой" задумок картодела

**Comment by Positiff88** [comment]
Как это не решает? Задумки картодела останутся на месте, ведь это они **переписывают** значения из новой глобальной настройки, а не наоборот.

**Comment by VladimirMakeev** [comment]
Что одно не очевидно, что другое. Если хочется сделать для своего мода такую логику - собери проект и внеси правки.

**Comment by Positiff88** [comment]
Добавь ещё пожалуйста глобальную настройку с количеством маны, добываемой за день столицами рас.
Иметь аналогичные переменные с добываемой столицами маной для карт тоже было бы полезно, пожалуй.

**Comment by Positiff88** [comment]
Я изначально решил, что ты собираешься добавить глобальные настройки дохода городов с логикой их добавления к переменным сценария, которую ты описывал. Но не могу найти коммита по этому поводу. Если он есть, то дай ссылку. Или же я неверно всё понял, и ты не планируешь их делать ни в каком виде?

**Comment by Positiff88** [comment]
Я реализовал данную фичу, включая возможность генерации маны. Вот коммит, если кому надо:
https://github.com/Positiff88/D2ModdingToolset/commit/1dadcac437e8545ebfa262c17fecf4d8fa1b1689
