### ISSUE TITLE
Multiple wards from one artefact

### ISSUE THREAD

**Issue by Positiff88** [VladimirMakeev/D2ModdingToolset#88]
Please add possibility to add multiple wards when one artefact is equipped by hero. For example, Weapon, Death and Poison wards at the same time.

Now if I add two lines with different wards (TYPE = 12 or TYPE = 14) into GmodifL.dbf for one modificator, which is specified in MOD_EQUIP column of  GItem.dbf, then only one ward from the last line is applied (while many bonuses for different stats works fine, for example, damage and initiative bonuses).

**Comment by UnveN** [comment]
@VladimirMakeev @Positiff88 Сделано в рамках кастомных модификаторов https://github.com/VladimirMakeev/D2ModdingToolset/commit/43c7eccba3d373d8bb715804f12c1b46cb5cc8f4

@Positiff88 Читай раздел "Supports custom unit modifiers" в https://github.com/VladimirMakeev/D2ModdingToolset#readme

**Comment by Positiff88** [comment]
Супер! Наконец-то смогу переделать Череп Танатоса в крутой защитный артефакт.
